[package]
name = "libvips-bindings"
description = "Safe bindings for libvips"
version = "1.1.2"
authors = ["Augusto César Dias <augusto.c.dias@gmail.com>"]
repository = "https://github.com/augustocdias/libvips-rust-bindings"
readme = "README.md"
license = "MIT"
edition = "2018"
keywords = ["libvips", "bindgen", "image", "bindings"]
categories = ["multimedia::images", "multimedia::encoding", "graphics"]

[build-dependencies]
bindgen = "0.53"
Inflector = "0.11"
cc = "1.0"
which = "3.1"

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
